### PR TITLE
Add `@rules_proto//proto:universal_tools` flag to allow building `protoc` as an universal binary

### PR DESCRIPTION
**Pull request by thii**
Similar to https://github.com/bazelbuild/rules_swift/pull/712

### CODE REVIEW

**Comment by Yannic** [comment]
I would really prefer to not add more dependencies. Hopefully, we can toolchainify proto rules soon, at which point it's very easy for users to provide their own protoc (like an universal binary)

**Comment by thii** [comment]
I can vendor that rule in rules_proto if you prefer that way.

**Comment by comius** [comment]
> I would really prefer to not add more dependencies. Hopefully, we can toolchainify proto rules soon, at which point it's very easy for users to provide their own protoc (like an universal binary)

I agree with that.

**Comment by thii** [comment]
That makes sense, I'm closing this. Looking forward to the proto rules toolchainification!

**Pull request closed without merging**
