### PR TITLE
Update @bazel_toolchains to v3.2.0

### PR DESCRIPTION
**Pull request by Yannic**

### CODE REVIEW

**Comment by Yannic** [comment]
#61 fixes the (unrelated) linter errors.

**Comment by hlopko** [comment]
(added the archive to bazel-mirror, and realized I cannot approve here anymore :)

**Comment by keith** [comment]
https://github.com/bazelbuild/rules_proto/pull/64

**Comment by Yannic** [comment]
Closing in favor of #64. Thanks @keith!

**Pull request closed without merging**
