### PR TITLE
doc: point users to the release page

### PR DESCRIPTION
**Pull request by alexeagle**
Otherwise the README has stale install instructions as it's not updated as part of the release process.

### CODE REVIEW

**Review by comius — APPROVED** [review]

**Comment by comius** [comment]
Thanks for the fix in json file also!

**Comment by comius** [comment]
cc @kotlaja, README file is not imported

**Comment by kotlaja** [comment]
cc @alexeagle, can you please resolve conflicts since I exported README file from blaze implementation (just add your change again)?

**Comment by alexeagle** [comment]
@kotlaja sure, I just told the GH UI to resolve the conflict

**Review by comius — APPROVED** [review]

**Pull request merged**
