### PR TITLE
Roll Protobuf to v3.10.0

### PR DESCRIPTION
**Pull request by Yannic**

### CODE REVIEW

**Comment by hlopko** [comment]
Hi I'm back :) So, can you write why is this needed? Also this is not a real protobuf release, is there a reason why we cannot wait for them to release?

Thanks for working on this!

**Comment by Yannic** [comment]
Great! Hope you had a good time off :).

The version we're pinning right now has a bug in its BUILD files that caused some tests to fail (https://buildkite.com/bazel/protobuf/builds/3038).
We're re using a specific hash because the latest release is not compatible with any of the `--incompatible_load_...` flags. We'll switch to 3.10 when that's available.

**Comment by Yannic** [comment]
Done. ptal

**Comment by Yannic** [comment]
Thanks!

@meteorcloudy Can you upload https://github.com/protocolbuffers/protobuf/archive/v3.10.0.tar.gz to bazel-mirror? Thanks!

**Comment by meteorcloudy** [comment]
Of course! It's done: https://mirror.bazel.build/github.com/protocolbuffers/protobuf/archive/v3.10.0.tar.gz

**Pull request merged**
